language: node_js
sudo: false
node_js:
  - 7
addons:
  apt:
    packages:
      - xvfb
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1366x768x24 > /dev/null 2>&1 &
script:
  - npm i
  - npm run build
  - npm run test
